version: '3.1'

services:
  postgres:
    container_name: fazt-postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fapi
      POSTGRES_PASSWORD: faztdb
    logging:
      driver: none
